# Generated by Django 5.0.6 on 2024-07-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_histories', to='shop.customer')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_histories', to='shop.mascota')),
            ],
        ),
    ]
