# Generated by Django 5.0.6 on 2024-07-01 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_emergencyhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='emergencyhistory',
            name='location',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencyhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='emergencyhistory',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mascota'),
        ),
    ]
